FROM python:3.10-slim

# set the working directory
WORKDIR /code

# install dependencies
COPY ./requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# copy the src to the folder
COPY ./src ./src

# start the server
# CMD ["python", "src.main", "--host", "0.0.0.0", "--port", "80", "--reload"]
CMD ["python3", "src.main.py"]